import { Icons } from "./icons";

const steps = [
  { number: "01", title: "Ingest target evidence", copy: "Open Jobs & mapping, choose the upload icon, enter the authoritative role title and upload the job-description files. Confirm source locations before continuing.", action: "Jobs & mapping → Ingest job description" },
  { number: "02", title: "Normalize work evidence", copy: "Separate responsibilities, outcomes, activities, tools, qualifications, context and constraints. Preserve the source quotation and page, slide, sheet or row for every normalized statement.", action: "Review Traceable job evidence" },
  { number: "03", title: "Clarify material ambiguity", copy: "Answer only evidence-changing questions about outcomes, autonomy, complexity, critical incidents and performance. Mapping unlocks at 80% sufficiency with no critical contradiction.", action: "Start adaptive clarification" },
  { number: "04", title: "Match approved skills first", copy: "The agent compares evidence with approved canonical skills, public KFLA metadata, internally authorized interpretations and controlled tools. Licensed definitions are used only after an authorized source is supplied.", action: "Run governed mapping" },
  { number: "05", title: "Build an 8–10 skill MECE profile", copy: "Give each responsibility or outcome one primary skill owner. Remove overlapping skill boundaries, cover every material statement and allocate exactly 100% profile weight.", action: "Inspect Profile quality gate" },
  { number: "06", title: "Design only genuine gaps", copy: "If no approved skill fits above threshold, propose a new Action + Object + Outcome skill. Include evidence, boundary, observability, duplicate analysis and confidence; never force a weak catalog match.", action: "Review taxonomy-gap drafts" },
  { number: "07", title: "Challenge confidence and evidence", copy: "Open Why this recommendation. Verify direct excerpts, thirteen score dimensions, alternatives, omissions, KFLA/tool links and the evidence-adjusted confidence interval.", action: "Review each mapping" },
  { number: "08", title: "Record accountable decisions", copy: "Confirm, adjust, reject or request evidence. A job architect validates role truth; a taxonomy steward validates skill identity. AI cannot approve or publish.", action: "Approve review-ready mappings" },
];

export function SkillMappingPlaybook({ onOpenJobs, onOpenReview }: { onOpenJobs: () => void; onOpenReview: () => void }) {
  return <div className="mapping-playbook">
    <section className="playbook-hero">
      <div><span className="section-kicker">ZM-13 · IN-APP METHODOLOGY</span><h2>From target job evidence to a governed skill profile.</h2><p>A reproducible method for deriving and mapping Korn Ferry-aligned skills without hiding evidence, uncertainty or human accountability.</p><div className="hero-actions"><button className="button primary" onClick={onOpenJobs}><Icons.arrow/>Start in Jobs & mapping</button><button className="button secondary" onClick={onOpenReview}>Open review queue</button></div></div>
      <div className="playbook-map" aria-label="Skill mapping methodology flow"><span>Evidence</span><i/><span>Clarify</span><i/><span>Match</span><i/><span>MECE profile</span><i/><span>Human review</span></div>
    </section>
    <section className="playbook-principles">
      <article><b>8–10</b><span>distinct role skills</span><small>Enough granularity to differentiate work without producing a task inventory.</small></article>
      <article><b>MECE</b><span>profile boundary</span><small>One primary owner per material statement; all responsibilities and outcomes covered.</small></article>
      <article><b>≥80%</b><span>evidence sufficiency</span><small>Mapping remains blocked while a critical contradiction or material evidence gap exists.</small></article>
      <article><b>Human</b><span>approval boundary</span><small>Agents draft and explain. Named job architects and taxonomy stewards decide.</small></article>
    </section>
    <section className="panel playbook-steps"><header><div><span className="section-kicker">CLICK GUIDE</span><h3>Execute the method step by step</h3></div></header>{steps.map((step) => <article key={step.number}><b>{step.number}</b><div><h4>{step.title}</h4><p>{step.copy}</p><code>{step.action}</code></div></article>)}</section>
    <section className="playbook-two-col">
      <article className="panel"><span className="section-kicker">MAPPING DECISION</span><h3>Match, abstain or design</h3><div className="decision-tree"><span><b>Approved skill fits ≥ threshold?</b><small>Yes → propose mapping with direct evidence.</small></span><i/><span><b>Evidence sufficient?</b><small>No → ask a bounded clarification question.</small></span><i/><span><b>Genuine capability gap?</b><small>Yes → create a governed new-skill draft.</small></span></div></article>
      <article className="panel"><span className="section-kicker">CORRECTNESS MODEL</span><h3>What reviewers must verify</h3><ul><li>Skill identity is durable, observable and non-duplicative.</li><li>Direct evidence supports the action, object and outcome.</li><li>All thirteen score dimensions are explained.</li><li>Confidence interval narrows as evidence completeness improves.</li><li>Rejected alternatives and omissions are explicit.</li><li>Licensed material remains access-controlled and source-owned.</li></ul></article>
    </section>
    <section className="panel playbook-example"><span className="section-kicker">WORKED EXAMPLE</span><h3>Cloud Platform Engineer</h3><div><blockquote>“Build and operate Azure landing zones and subscriptions.”</blockquote><span>Normalized outcome</span><b>Operate governed cloud foundations</b><span>Candidate skill</span><b>Cloud platform engineering</b><span>Decision evidence</span><b>Direct source row + approved taxonomy boundary + tool relevance</b></div><p>The statement receives one primary skill owner. Azure is retained as controlled-tool evidence, not mistaken for the skill itself. Supporting behaviors belong to separate competency mappings only when they have distinct evidence.</p></section>
    <section className="panel playbook-help"><span className="section-kicker">TROUBLESHOOTING</span><details><summary>The agent returns no mappings</summary><p>Check the authoritative role title, resolve critical contradictions, reach the clarification threshold and verify that normalized responsibilities/outcomes exist. A valid abstention should produce omissions or taxonomy-gap drafts—not a silent empty result.</p></details><details><summary>The profile has fewer than eight skills</summary><p>Inspect uncovered evidence. Clarify weak statements, map an approved concept, or route a genuine capability gap to taxonomy review. Do not pad the profile with weak matches.</p></details><details><summary>The profile is not MECE</summary><p>Open the profile quality gate. Reassign overlapping evidence to one primary skill and define clearer inclusion/exclusion boundaries for competing skills.</p></details><details><summary>Confidence is too broad</summary><p>Add direct outcome evidence, observable critical incidents, proficiency anchors and authoritative source locations. Never raise confidence only to pass review.</p></details></section>
  </div>;
}
