"use client";

import { useState } from "react";
import { Icons } from "./icons";
import type { StrategicVector, SkillWorkspace } from "@/lib/skill-schema";

export function StrategicVectors({ workspace, mutate }: { workspace: SkillWorkspace; mutate: (update: (current: SkillWorkspace) => SkillWorkspace) => void }) {
  const [editing, setEditing] = useState<StrategicVector | "new" | null>(null);
  const mappingsFor = (id: string) => workspace.mappings.filter((item) => item.strategicVectorIds.includes(id)).length;
  return <div className="vector-workbench"><section className="vector-hero"><div><span>STRATEGIC SKILL VECTORS</span><h2>Translate strategy into capability demand.</h2><p>Vectors are governed, time-bound themes that enrich role profiles without creating a second taxonomy.</p></div><button className="button primary" onClick={() => setEditing("new")}><Icons.plus/>Create vector</button></section><section className="vector-grid">{workspace.strategicVectors.map((vector) => <article className="panel vector-card" key={vector.id}><header><span className={`vector-priority ${vector.priority}`}>{vector.priority}</span><div className="record-actions"><button aria-label={`Edit ${vector.name}`} onClick={() => setEditing(vector)}><Icons.edit/></button><button aria-label={`Delete ${vector.name}`} onClick={() => mutate((current) => ({ ...current, strategicVectors: current.strategicVectors.filter((item) => item.id !== vector.id), mappings: current.mappings.map((item) => ({ ...item, strategicVectorIds: item.strategicVectorIds.filter((id) => id !== vector.id) })) }))}><Icons.trash/></button></div></header><h3>{vector.name}</h3><p>{vector.description}</p><div className="vector-stats"><span><b>{vector.skillIds.length}</b><small>catalog skills</small></span><span><b>{mappingsFor(vector.id)}</b><small>job mappings</small></span><span><b>{vector.horizon}</b><small>horizon</small></span></div><div className="vector-skills">{vector.skillIds.map((id) => <span key={id}>{workspace.skills.find((skill) => skill.id === id)?.name || id}</span>)}{!vector.skillIds.length && <small>No catalog skills linked yet.</small>}</div></article>)}</section><section className="panel vector-rules"><div><span className="section-kicker">APPLICATION LOGIC</span><h3>Vectors enrich roles; they do not replace job evidence</h3></div>{[["01", "Evidence baseline", "Map capabilities required by current accountabilities."], ["02", "Strategic uplift", "Add only capabilities clearly connected to an approved vector."], ["03", "Profile discipline", "Keep the final role profile to a maximum of 10 pilot skills."], ["04", "Time horizon", "Separate foundational capability from differentiating future demand."]].map(([step, name, copy]) => <div key={step}><b>{step}</b><span><strong>{name}</strong><small>{copy}</small></span></div>)}</section>{editing && <VectorEditor vector={editing === "new" ? { id: "", name: "", description: "", horizon: "2026–2029", priority: "accelerate", skillIds: [], status: "draft" } : editing} workspace={workspace} onClose={() => setEditing(null)} onSave={(value) => { mutate((current) => ({ ...current, strategicVectors: value.id ? current.strategicVectors.map((item) => item.id === value.id ? value : item) : [{ ...value, id: `VEC-${Date.now()}` }, ...current.strategicVectors] })); setEditing(null); }}/>}</div>;
}

function VectorEditor({ vector, workspace, onClose, onSave }: { vector: StrategicVector; workspace: SkillWorkspace; onClose: () => void; onSave: (vector: StrategicVector) => void }) {
  const [value, setValue] = useState(vector);
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onMouseDown={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); onSave(value); }}><header><div><span className="section-kicker">STRATEGIC VECTOR</span><h2>{vector.id ? `Edit ${vector.name}` : "Create strategic vector"}</h2></div><button type="button" className="icon-button" onClick={onClose}><Icons.close/></button></header><label><span>Name</span><input required value={value.name} onChange={(event) => setValue((current) => ({ ...current, name: event.target.value }))}/></label><label><span>Strategic intent</span><textarea required value={value.description} onChange={(event) => setValue((current) => ({ ...current, description: event.target.value }))}/></label><div className="form-row"><label><span>Horizon</span><input required value={value.horizon} onChange={(event) => setValue((current) => ({ ...current, horizon: event.target.value }))}/></label><label><span>Priority</span><select value={value.priority} onChange={(event) => setValue((current) => ({ ...current, priority: event.target.value as StrategicVector["priority"] }))}>{["foundational", "accelerate", "differentiate"].map((item) => <option key={item}>{item}</option>)}</select></label></div><fieldset className="skill-checkboxes"><legend>Catalog skills</legend>{workspace.skills.filter((skill) => skill.status === "approved").map((skill) => <label key={skill.id}><input type="checkbox" checked={value.skillIds.includes(skill.id)} onChange={() => setValue((current) => ({ ...current, skillIds: current.skillIds.includes(skill.id) ? current.skillIds.filter((id) => id !== skill.id) : [...current.skillIds, skill.id] }))}/><span>{skill.name}</span></label>)}</fieldset><footer><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary">Save vector</button></footer></form></div>;
}
