"use client";

import { useState } from "react";
import { Icons } from "./icons";
import { recordGovernedVersion } from "@/lib/skill-governance";
import type { StrategicVector, SkillWorkspace } from "@/lib/skill-schema";

export function StrategicVectors({ workspace, mutate }: { workspace: SkillWorkspace; mutate: (update: (current: SkillWorkspace) => SkillWorkspace) => void }) {
  const [editing, setEditing] = useState<StrategicVector | "new" | null>(null);
  const [archiving, setArchiving] = useState<{ vector: StrategicVector; nextStatus: "draft" | "archived" } | null>(null);
  const mappingsFor = (id: string) => workspace.mappings.filter((item) => item.strategicVectorIds.includes(id)).length;
  function save(value: StrategicVector, actor: string, reason: string) {
    const id = value.id || `VEC-${Date.now()}`;
    const exists = workspace.strategicVectors.some((item) => item.id === id);
    const saved = { ...value, id, status: exists && value.status === "approved" ? "in_review" as const : value.status };
    mutate((current) => recordGovernedVersion({ ...current, strategicVectors: exists ? current.strategicVectors.map((item) => item.id === id ? saved : item) : [saved, ...current.strategicVectors] }, "strategic_vector", id, exists ? "strategic_vector.updated" : "strategic_vector.created", actor.trim(), { ...saved, governanceReason: reason.trim() } as unknown as Record<string, unknown>));
    setEditing(null);
  }
  function archive(actor: string, reason: string) {
    if (!archiving) return;
    const affectedMappings = mappingsFor(archiving.vector.id);
    mutate((current) => recordGovernedVersion({ ...current, strategicVectors: current.strategicVectors.map((item) => item.id === archiving.vector.id ? { ...item, status: archiving.nextStatus } : item), mappings: current.mappings.map((item) => item.strategicVectorIds.includes(archiving.vector.id) ? { ...item, status: "proposed" } : item) }, "strategic_vector", archiving.vector.id, `strategic_vector.${archiving.nextStatus === "archived" ? "archived" : "restored"}`, actor.trim(), { ...archiving.vector, nextStatus: archiving.nextStatus, governanceReason: reason.trim(), affectedMappings, referencesPreserved: true } as unknown as Record<string, unknown>));
    setArchiving(null);
  }
  return <div className="vector-workbench"><section className="vector-hero"><div><span>STRATEGIC SKILL VECTORS</span><h2>Translate strategy into capability demand.</h2><p>Vectors are governed, time-bound themes that enrich role profiles without creating a second taxonomy.</p></div><button className="button primary" onClick={() => setEditing("new")}><Icons.plus/>Create vector</button></section><section className="vector-grid">{workspace.strategicVectors.map((vector) => <article className="panel vector-card" key={vector.id}><header><span className={`vector-priority ${vector.priority}`}>{vector.priority} · {vector.status}</span><div className="record-actions"><button aria-label={`Edit ${vector.name}`} onClick={() => setEditing(vector)}><Icons.edit/></button><button aria-label={`${vector.status === "archived" ? "Restore" : "Archive"} ${vector.name}`} onClick={() => setArchiving({ vector, nextStatus: vector.status === "archived" ? "draft" : "archived" })}>{vector.status === "archived" ? <Icons.refresh/> : <Icons.trash/>}</button></div></header><h3>{vector.name}</h3><p>{vector.description}</p><div className="vector-stats"><span><b>{vector.skillIds.length}</b><small>catalog skills</small></span><span><b>{mappingsFor(vector.id)}</b><small>job mappings</small></span><span><b>{vector.horizon}</b><small>horizon</small></span></div><div className="vector-skills">{vector.skillIds.map((id) => <span key={id}>{workspace.skills.find((skill) => skill.id === id)?.name || id}</span>)}{!vector.skillIds.length && <small>No catalog skills linked yet.</small>}</div></article>)}</section><section className="panel vector-rules"><div><span className="section-kicker">APPLICATION LOGIC</span><h3>Vectors enrich roles; they do not replace job evidence</h3></div>{[["01", "Evidence baseline", "Map capabilities required by current accountabilities."], ["02", "Strategic uplift", "Add only capabilities clearly connected to an approved vector."], ["03", "Profile discipline", "Keep the final role profile to a maximum of 10 pilot skills."], ["04", "Time horizon", "Separate foundational capability from differentiating future demand."]].map(([step, name, copy]) => <div key={step}><b>{step}</b><span><strong>{name}</strong><small>{copy}</small></span></div>)}</section>{editing && <VectorEditor vector={editing === "new" ? { id: "", name: "", description: "", horizon: "2026–2029", priority: "accelerate", skillIds: [], status: "draft" } : editing} workspace={workspace} onClose={() => setEditing(null)} onSave={save}/>} {archiving && <VectorLifecycleEditor vector={archiving.vector} nextStatus={archiving.nextStatus} affectedMappings={mappingsFor(archiving.vector.id)} onClose={() => setArchiving(null)} onSave={archive}/>}</div>;
}

function VectorEditor({ vector, workspace, onClose, onSave }: { vector: StrategicVector; workspace: SkillWorkspace; onClose: () => void; onSave: (vector: StrategicVector, actor: string, reason: string) => void }) {
  const [value, setValue] = useState(vector);
  const [actor, setActor] = useState(""); const [reason, setReason] = useState("");
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onMouseDown={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); onSave(value, actor, reason); }}><header><div><span className="section-kicker">STRATEGIC VECTOR</span><h2>{vector.id ? `Edit ${vector.name}` : "Create strategic vector"}</h2></div><button type="button" className="icon-button" onClick={onClose}><Icons.close/></button></header><label><span>Name</span><input required value={value.name} onChange={(event) => setValue((current) => ({ ...current, name: event.target.value }))}/></label><label><span>Strategic intent</span><textarea required value={value.description} onChange={(event) => setValue((current) => ({ ...current, description: event.target.value }))}/></label><div className="form-row"><label><span>Horizon</span><input required value={value.horizon} onChange={(event) => setValue((current) => ({ ...current, horizon: event.target.value }))}/></label><label><span>Priority</span><select value={value.priority} onChange={(event) => setValue((current) => ({ ...current, priority: event.target.value as StrategicVector["priority"] }))}>{["foundational", "accelerate", "differentiate"].map((item) => <option key={item}>{item}</option>)}</select></label></div><fieldset className="skill-checkboxes"><legend>Catalog skills</legend>{workspace.skills.filter((skill) => skill.status === "approved").map((skill) => <label key={skill.id}><input type="checkbox" checked={value.skillIds.includes(skill.id)} onChange={() => setValue((current) => ({ ...current, skillIds: current.skillIds.includes(skill.id) ? current.skillIds.filter((id) => id !== skill.id) : [...current.skillIds, skill.id] }))}/><span>{skill.name}</span></label>)}</fieldset><div className="form-row"><label><span>Accountable actor</span><input required value={actor} onChange={(event) => setActor(event.target.value)}/></label><label><span>Governance reason</span><textarea required value={reason} onChange={(event) => setReason(event.target.value)}/></label></div><footer><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary">Save vector</button></footer></form></div>;
}

function VectorLifecycleEditor({ vector, nextStatus, affectedMappings, onClose, onSave }: { vector: StrategicVector; nextStatus: "draft" | "archived"; affectedMappings: number; onClose: () => void; onSave: (actor: string, reason: string) => void }) {
  const [actor, setActor] = useState(""); const [reason, setReason] = useState("");
  return <div className="modal-backdrop"><form className="modal-card" onSubmit={(event) => { event.preventDefault(); onSave(actor, reason); }}><header><div><span className="section-kicker">VECTOR IMPACT & HISTORY</span><h3>{nextStatus === "archived" ? "Archive" : "Restore"} {vector.name}</h3></div><button type="button" onClick={onClose}><Icons.close/></button></header><p>{affectedMappings} job mappings reference this vector. References are preserved and affected mappings return to review.</p><label><span>Accountable actor</span><input required value={actor} onChange={(event) => setActor(event.target.value)}/></label><label><span>Governance reason</span><textarea required value={reason} onChange={(event) => setReason(event.target.value)}/></label><footer><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Apply vector lifecycle</button></footer></form></div>;
}
